version: '3.8'
services:
  app:
    build: .
    image: this_is_a_test
    environment:
      NODE_ENV: development
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6

